# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Longuet NZ
email: geoff@longuet.nz
description: > # this means to ignore newlines until "baseurl:"
  Longuet NZ - Software Development.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://longuet.nz" # the base hostname & protocol for your site
exclude: ['bower_components/*.md']
#twitter_username: jekyllrb
#github_username:  jekyll

# Build settings
markdown: kramdown
sass:
    sass_dir: ./css
    style: compressed

#sass:
#  load_paths:
#    - bower_components/bootstrap/scss
#    - bower_components/font-awesome/scss
#  style: compressed