version: '3'
services:
  jekyll:
    image: jekyll/minimal
    volumes:
      - .:/srv/jekyll
    ports:
      - "4000:4000"
    command: ["jekyll", "serve", "--force-polling", "--config", "_config.yml"]